"""empty message

Revision ID: 4a847f812a3e
Revises: 6561512ce36c
Create Date: 2025-02-17 19:33:27.928862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a847f812a3e'
down_revision = '6561512ce36c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interest_point',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('int_name', sa.String(length=100), nullable=False),
    sa.Column('locality', sa.String(length=100), nullable=False),
    sa.Column('point_address', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interest_point')
    # ### end Alembic commands ###
