"""empty message

Revision ID: 57a8fb4b8e7c
Revises: 
Create Date: 2025-02-21 19:20:40.777599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57a8fb4b8e7c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('city',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_name', sa.String(length=30), nullable=False),
    sa.Column('country_name', sa.String(length=30), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hotel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hotel_name', sa.String(length=50), nullable=False),
    sa.Column('hotel_address', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interest_point',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('int_name', sa.String(length=100), nullable=False),
    sa.Column('locality', sa.String(length=100), nullable=False),
    sa.Column('point_address', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('restaurant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_name', sa.String(length=30), nullable=False),
    sa.Column('address', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('favorites_user_id', sa.Integer(), nullable=True),
    sa.Column('favorites_city_id', sa.Integer(), nullable=True),
    sa.Column('favorites_hotel_id', sa.Integer(), nullable=True),
    sa.Column('favorites_restaurant_id', sa.Integer(), nullable=True),
    sa.Column('favorites_interest_point_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['favorites_city_id'], ['city.id'], ),
    sa.ForeignKeyConstraint(['favorites_hotel_id'], ['hotel.id'], ),
    sa.ForeignKeyConstraint(['favorites_interest_point_id'], ['interest_point.id'], ),
    sa.ForeignKeyConstraint(['favorites_restaurant_id'], ['restaurant.id'], ),
    sa.ForeignKeyConstraint(['favorites_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    op.drop_table('restaurant')
    op.drop_table('interest_point')
    op.drop_table('hotel')
    op.drop_table('city')
    op.drop_table('user')
    # ### end Alembic commands ###
