"""empty message

Revision ID: 93e2e6b5229e
Revises: 0620bcac1bea
Create Date: 2025-02-28 13:24:52.726634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93e2e6b5229e'
down_revision = '0620bcac1bea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites_city', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorites_user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('favorites_city_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('favorites_city_city_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('favorites_city_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['favorites_user_id'], ['id'])
        batch_op.create_foreign_key(None, 'city', ['favorites_city_id'], ['id'])
        batch_op.drop_column('user_id')
        batch_op.drop_column('city_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites_city', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorites_city_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key('favorites_city_city_id_fkey', 'city', ['city_id'], ['id'])
        batch_op.drop_column('favorites_city_id')
        batch_op.drop_column('favorites_user_id')

    # ### end Alembic commands ###
