"""empty message

Revision ID: 988eca44f41e
Revises: 7c0c21075b52
Create Date: 2025-02-17 19:34:45.855668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '988eca44f41e'
down_revision = '7c0c21075b52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('favorites_user_id', sa.Integer(), nullable=True),
    sa.Column('favorites_city_id', sa.Integer(), nullable=True),
    sa.Column('favorites_hotel_id', sa.Integer(), nullable=True),
    sa.Column('favorites_restaurant_id', sa.Integer(), nullable=True),
    sa.Column('favorites_interest_point_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['favorites_city_id'], ['city.id'], ),
    sa.ForeignKeyConstraint(['favorites_hotel_id'], ['hotel.id'], ),
    sa.ForeignKeyConstraint(['favorites_interest_point_id'], ['interest_point.id'], ),
    sa.ForeignKeyConstraint(['favorites_restaurant_id'], ['restaurant.id'], ),
    sa.ForeignKeyConstraint(['favorites_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    # ### end Alembic commands ###
