"""empty message

Revision ID: aa9b06e311bd
Revises: c2b3e4658e47
Create Date: 2025-02-18 18:08:36.251732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa9b06e311bd'
down_revision = 'c2b3e4658e47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=False))
        batch_op.drop_column('mame')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mame', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_column('name')

    # ### end Alembic commands ###
